name: Build

env:
  PROJECT_NAME: "ChangeMe"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "${{ matrix.variants.runner }}/${{ matrix.variants.arch }}/${{ matrix.variants.config }}"
    env:
      NB_CPU: 1

    strategy:
      fail-fast: false
      matrix:
        variants:
          - {runner: windows-2022,   arch: x64,      config: RelWithDebInfo}
          - {runner: windows-2022,   arch: win32,    config: RelWithDebInfo}
          - {runner: windows-2022,   arch: arm64,    config: RelWithDebInfo}
          - {runner: windows-2022,   arch: arm,      config: RelWithDebInfo}

    runs-on: ${{ matrix.variants.runner }}
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Import-Module .\.github\Invoke-VisualStudio.ps1; Invoke-VisualStudio2022${{ matrix.variants.arch }}
    # - run: choco install gnuwin32-m4
    - run: winget install GnuWin32.M4
    - run: cmake -S . -B ./build -A ${{ matrix.variants.arch }}
    - run: cmake --build ./build --parallel ${{ env.NB_CPU }} --config ${{ matrix.variants.config }}
    - run: cmake --install ./build --config ${{ matrix.variants.config }} --prefix ./artifact --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}_${{ matrix.variants.arch }}_${{ matrix.variants.runner }}_${{ matrix.variants.config }}_${{ github.sha }}_${{ matrix.variants.build }}
        path: artifact/
